name: First WorkFlow Ex
<<<<<<< HEAD
on: pull_request
=======
on: [push,pull_request]
>>>>>>> f800ae17e08175103f5de8b093fb91bc18697d81
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a String
        run: echo "Hello World First GitHubAction Program"
      - name: Multiline Script
        run: |
         node -v
         npm -v
      - name: Python Command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-power-shell-commands:
    runs-on: windows-latest
    needs: [run-shell-commands]
    steps:
      - name: Directory Bash
        run: pwd
      - name: Directory Power shell
        run: Get-Location
      